### ISSUE TITLE
Mail attachments have zero bytes, wont open

### ISSUE THREAD

**Issue by SandyMental** [FriendsOfShopware/FroshMailArchive#4] opened 2019-01-23 14:00 UTC
if the  plug-in is active, attachments send via Shopware (for example the Pickware document mails) come with zero bytes and therefore wont open.
any suggestions? I know the problem most probably is on our side, I just need a hint where to start fixing that one.

**Comment by tinect** [comment] 2019-01-23 14:06
hi @SandyMental 

Thank you for contacting.

Let me ask some more: Are they delivered with 0byte, if the plugin is active or `just` coming from MailArchive with 0 byte?

Thank you.

**Comment by SandyMental** [comment] 2019-01-23 14:11
they are delivered with 0byte when the plugin is active

**Comment by shyim** [comment] 2019-01-23 14:17
I guess the issue is that **just** the mail is cloned and not the attachments https://github.com/FriendsOfShopware/FroshMailArchive/blob/master/Subscriber/OnMailSubscriber.php#L74

**Comment by tinect** [comment] 2019-01-23 16:16
Hi @SandyMental 
Just to be safe: But in MailArchive the attachments are correct?
Currently I cannot reproduce this error. We will check shortly what we can do.

**Comment by SandyMental** [comment] 2019-01-23 16:23
nope, same error.
Later this week I got more time for testing if some other plug-in is causing this one.

You dont need to rush on this one. at least it is a free plug-in.
You guys did and are doing a great job with your plug-ins :)

**Comment by buddhaCode** [comment] 2019-01-23 16:28
I have the same problem with MailCatcher. In my case the attachments are not written the database. The content column is empty.
Mail ID 3123 is a document send via pickware erp. Mail ID 3117 is a notification for a state change.
HTH.
![bildschirmfoto 2019-01-23 um 17 23 03](https://user-images.githubusercontent.com/11678100/51620890-a5628080-1f33-11e9-94e1-646dd25891cc.png)

**Comment by buddhaCode** [comment] 2019-01-23 16:29
> I guess the issue is that **just** the mail is cloned and not the attachments https://github.com/FriendsOfShopware/FroshMailArchive/blob/master/Subscriber/OnMailSubscriber.php#L74

Yeah, I guess you need to create a deep clone. But this would not explain my issue.

**Comment by shyim** [comment] 2019-01-23 18:18
@SandyMental @buddhaCode
Could you test the referenced Commit? **AND** deactivate the plugin until its fixed with PickwareERP

PS: SandyMental cool Profil bio :3

**Comment by tinect** [comment] 2019-01-23 20:33
@shyim ist to fast for me, thank you! :-)

As shyim says, it'll be great if you could check with referenced commit. Tell me if there is a problem for to change the files, so I will add a zip you can upload to pluginmanager for you. Thank you for testing!

**Comment by SandyMental** [comment] 2019-01-24 08:32
@shyim  @tinect 

it works! thank you guys :)

**Comment by tinect** [comment] 2019-01-24 09:15
@SandyMental Thank you, too! Will publish a new version in store later this day :-)

**Closed as completed** 2019-01-24 10:16 UTC
Labels: kind/bug
